Prevent duplicate notifications during job re-processing
cds-snc/notification-api pull request #1912
Opened 2023-06-26 20:45 UTC by whabanks

# Summary | Résumé

> 1-3 sentence description of the changed you're proposing, including a link to
> a GitHub Issue # or Trello card if applicable.

---

> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le
> problème (« issue ») GitHub ou la fiche Trello, le cas échéant.

# Test instructions | Instructions pour tester la modification

> Sequential steps (1., 2., 3., ...) that describe how to test this change. This
> will help a developer test things out without too much detective work. Also,
> include any environmental setup steps that aren't in the normal README steps
> and/or any time-based elements that this requires.

---

> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la
> modification. Elles aideront les développeurs à faire des tests sans avoir à
> jouer au détective. Veuillez aussi inclure toutes les étapes de configuration
> de l’environnement qui ne font pas partie des étapes normales dans le fichier
> README et tout élément temporel requis.

# Release Instructions | Instructions pour le déploiement

None.

> Necessary steps to perform before and after the deployment of these changes.
> For example, emptying the cache on a feature that changes the cache data
> structure in Redis could be mentioned.

---

> Étapes nécessaires à exécuter avant et après le déploiement des changements
> introduits par cette proposition. Par exemple, vider la cache suite à des
> changements modifiant une structure de données de la cache pourrait être
> mentionné.

# Reviewer checklist | Liste de vérification du réviseur

This is a suggested checklist of questions reviewers might ask during their
review | Voici une suggestion de liste de vérification comprenant des questions
que les réviseurs pourraient poser pendant leur examen :

- [ ] Is the code maintainable? | Est-ce que le code peut être maintenu?
- [ ] Have you tested it? | L’avez-vous testé?
- [ ] Are there automated tests? | Y a-t-il des tests automatisés?
- [ ] Does this cause automated test coverage to drop? | Est-ce que ça entraîne
      une baisse de la quantité de code couvert par les tests automatisés?
- [ ] Does this break existing functionality? | Est-ce que ça brise une
      fonctionnalité existante?
- [ ] Does this change the privacy policy? | Est-ce que ça entraîne une
      modification de la politique de confidentialité?
- [ ] Does this introduce any security concerns? | Est-ce que ça introduit des
      préoccupations liées à la sécurité?
- [ ] Does this significantly alter performance? | Est-ce que ça modifie de
      façon importante la performance?
- [ ] What is the risk level of using added dependencies? | Quel est le degré de
      risque d’utiliser des dépendances ajoutées?
- [ ] Should any documentation be updated as a result of this? (i.e. README
      setup, etc.) | Faudra-t-il mettre à jour la documentation à la suite de ce
      changement (fichier README, etc.)?

2023-06-30 13:37 UTC, smcmurtry commented
Okay I've made a bit of progress on testing this with the debugger:

By the time we get to L191 of notifications_dao.py, the job is already marked as finished in the job table in the db. This seems weird since no notifications have been sent at this point. Because the job has already been marked as finished at this point, pausing here will not trigger the `check_job_status` in scheduled_tasks.py to restart the job since that task only checks for jobs that are still in progress.

2023-06-30 13:48 UTC, smcmurtry commented
It looks like this is a bug - the job is being marked as "finished" too early.
In `process_job` and `process_incomplete_job` in `tasks.py`, we have the following flow:

1. call `process_rows` on all chunk of the total rows for the job
2.  mark the job as complete with `job_complete`

This probably worked correctly if `process_rows` used to not be async. But now `process_rows` is async because it calls `save_emails.apply_async` or `save_smss.apply_async`. So those processes can still be in progress at the time we mark the job as complete.

2023-06-30 14:01 UTC, smcmurtry requested changes
I don't think this is going to work unless we first fix the bug where the job is marked `"complete"` too early.

2023-07-04 14:41 UTC, smcmurtry commented
Also - I was not able to reproduce the "duplicate notifications" bug using the steps above.

2023-07-06 16:13 UTC, smcmurtry approved these changes
Code looks good. I created a new issue for [jobs getting marked finished to soon](https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1275).

2023-07-06 16:39 UTC, merged

2023-07-13 12:49 UTC, jimleroyer commented on app/celery/tasks.py
> +def update_job(job_id):
The celery task receives a job ID here..