Fix TC deletion bug
cds-snc/notification-api pull request #2233
Opened 2024-07-25 20:01 UTC by whabanks

# Summary | Résumé
This PR fixes an issue where a Template Category could not be deleted following deletion of the templates it was associated with. 

When a user "deletes" a template the template is marked as `archived` rather than deleted and removed from the templates table, preventing deletion.

`dao_delete_template_category_by_id` now checks if the category is ONLY associated with archived templates. If that is the case, we set the archived template's `template_category_id` to `null` and proceed with deleting the template category. 

A side effect of this is that the `templates_history` table will contain rows with references to categories that no longer exist and cannot ever be cross referenced as we do not have a `template_category_history` table.

## Related Issues | Cartes liées
This issue was uncovered during the template categories bug bash and is documented below
https://docs.google.com/document/d/1swqV2sKYBZB9UHKjXsspPSp6SEJSBWVxmbAcUKFu5Ts/edit#task=OuE8AO3ICha-9aYF

# Test instructions | Instructions pour tester la modification

1. Create a new template category
2. Associate the category with 1 template
3. Delete the template
4. Delete the template category
5. The delete should succeed
6. Verify in the DB that the archived template's `template_category_id` is set to `null`

# Reviewer checklist | Liste de vérification du réviseur

- [ ] This PR does not break existing functionality.
- [ ] This PR does not violate GCNotify's privacy policies.
- [ ] This PR does not raise new security concerns. Refer to our GC Notify Risk Register document on our Google drive.
- [ ] This PR does not significantly alter performance.
- [ ] Additional required documentation resulting of these changes is covered (such as the README, setup instructions, a related ADR or the technical documentation).

> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For example, changes to celery code may require tests on staging to verify that performance has not been affected.

2024-07-25 20:06 UTC, sastels commented
Should we also null out the `template_category_id` in the affected rows of `templates_history`?

2024-07-25 20:19 UTC, whabanks commented
> Should we also null out the `template_category_id` in the affected rows of `templates_history`? Seems bad to leave the database in a state where looking up things might fail.

Agreed, we can null it as you suggested or if we want to preserve the priority / `process_type` in history we could:

2. Set `template_category_id` in history to one of the generic categories that maps to the `process_type` of the deleted category
3. Null the `template_category_id` in the history table but set the `process_type` to the one corresponding to the deleted category. (This might be misleading as `process_type` is intended as an override now)

2024-07-25 20:59 UTC, jzbahrai approved these changes

2024-07-29 14:22 UTC, jzbahrai requested changes
I am wondering if we should have an archived flag.. instead. You can't delete a category - it just goes into archived on the template category table. I am not a fan of losing history

2024-07-29 14:59 UTC, whabanks commented
> I am wondering if we should have an archived flag.. instead. You can't delete a category - it just goes into archived on the template category table. I am not a fan of losing history

Neat idea, it would require some more front end work but I can certainly get the back end ready with this PR.

2024-07-29 17:01 UTC, jzbahrai commented
We are going to shut this PR, to be revisited when we add the archiving functionality

2024-07-29 17:01 UTC, closed without merging