Func to find service annual stats and send an email
cds-snc/notification-api pull request #2359
Opened 2024-11-14 21:59 UTC by jzbahrai

# Summary | Résumé

_TODO: 1-3 sentence description of the changed you're proposing._

## Related Issues | Cartes liées

* https://app.zenhub.com/workspaces/notify-planning-614b3ad91bc2030015ed22f5/issues/gh/cds-snc/notification-planning/1
* https://app.zenhub.com/workspaces/notify-planning-core-6411dfb7c95fb80014e0cab0/issues/gh/cds-snc/notification-planning-core/1

# Test instructions | Instructions pour tester la modification

_TODO: Fill in test instructions for the reviewer._

# Release Instructions | Instructions pour le déploiement

None.

# Reviewer checklist | Liste de vérification du réviseur

- [ ] This PR does not break existing functionality.
- [ ] This PR does not violate GCNotify's privacy policies.
- [ ] This PR does not raise new security concerns. Refer to our GC Notify Risk Register document on our Google drive.
- [ ] This PR does not significantly alter performance.
- [ ] Additional required documentation resulting of these changes is covered (such as the README, setup instructions, a related ADR or the technical documentation).

> ⚠ If boxes cannot be checked off before merging the PR, they should be moved to the "Release Instructions" section with appropriate steps required to verify before release. For example, changes to celery code may require tests on staging to verify that performance has not been affected.

2024-11-15 17:36 UTC, jzbahrai commented on app/celery/reporting_tasks.py
> +                send_annual_usage_data(user_id, email_address, markdown_list_en, markdown_list_fr)
this will not work as we don't have the template in the DB

2024-11-20 14:43 UTC, yaelberger-commits commented
Email looks as it should and as long as the data in it is cumulative throughout the year, so Q3 report includes volume from Q1 and Q2 as well as Q3, we're good!

2024-11-20 15:29 UTC, whabanks requested changes
Tested locally with the provided REPL commands and received the email as expected. One question, for services without data in the `annual_limits_data` table we should probably populate it with 0's

![image](https://github.com/user-attachments/assets/529e4300-a7fb-41cb-8b59-5c709007624b)

Becomes:
![image](https://github.com/user-attachments/assets/ee1e7a1d-8a14-4ef3-8cf7-bbc056008ed5)

Other than that, LGTM!

2024-11-20 20:20 UTC, whabanks approved these changes
LGTM!

2024-11-20 20:22 UTC, merged